language: java

jdk:
- oraclejdk8

sudo: false

before_install:
  - sudo apt-get sudo apt-get update -qq
  - sudo apt-get install --only-upgrade -y oracle-java8-installer

# Build everything in 'script' phase
install: /bin/true

script:
  - mvn clean install -X

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - master
